Updates for Cacti 1.x compatibility
thurban/plugin_weathermap pull request #39
Opened 2022-12-31 19:01 UTC by TheWitness

This is a large update to the Weathermap functionality that brings full support to Cacti 1.x, a few security issues and a rash of updated functionality.  See the CHANGELOG.md for details.  Consider this a BETA pull request.

2022-12-31 21:10 UTC, thurban submitted a review, later dismissed
Great work.

2023-01-01 16:22 UTC, TheWitness commented
Okay, did a few updates to capture some of @thurban comments, remove some remaining legacy getopt calls and on check and added some, but not all `display_version()` and `display_help()` functions for CLI's.

2023-01-02 17:04 UTC, cigamit commented
![Screenshot_4](https://user-images.githubusercontent.com/957322/210261070-acd6816c-ba4f-4f68-8b98-725bf4d8df3b.png)
When attempting to delete a link, the dialog says Node on the button

2023-01-02 17:05 UTC, cigamit commented
![Screenshot_3](https://user-images.githubusercontent.com/957322/210261132-372e9f66-5eb8-4446-be75-dda09b7214fa.png)
If you had a custom image in the base image directory, it wants to move it, and fails when it doesn't have permissions.  I would expect these errors to show in the log instead of in the editor.

2023-01-04 01:09 UTC, netniV requested changes
We should probably insert our own copyright for the work we do, on top o forwards.  Also, the years probably need updating on each element now.  Check for any db statements not using prepared statements.

2023-01-04 01:09 UTC, netniV commented on CHANGELOG.md
> +IMPORTANT NOTE: This version only works on CACTI 1.x++!
Inconsistency between important note usage

2023-01-04 01:09 UTC, netniV commented on CHANGELOG.md
> +* FIXED  - General support for PHP 8.2
Should list which Weathermap Core is supported

2023-01-04 01:09 UTC, netniV commented on CHANGELOG.md
> +* ADDED  - Drop image functionality for Nodes and Background images
Style inconsistent with other Cacti maintained plugins

2023-01-04 01:09 UTC, netniV commented on README.md
> +This is PHP Network Weathermap fork, version 1.0 originally by Howard Jones (howie@thingy.com)
v1.0 wasn't originally written by Howie, but based on Howie's work.

2023-01-04 01:09 UTC, netniV commented on README.md
> +
Inconsistent markdown levels

2023-01-04 01:09 UTC, netniV commented on cli/cacti-mapper.php
> +$data_template_hash = 'fd841e8bb822927289b7acbc031f3d7e';
This may not be right? If so, should it be overridable without editing?

2023-01-04 01:09 UTC, netniV commented on cli/cacti-mapper.php
> +
Is this in a writable folder? It would be in the cacti root folder if I understand the code correctly thus far.

2023-01-04 01:09 UTC, netniV commented on cli/cacti-mapper.php
> +$fd = fopen('mapper-cache.txt', 'w');
Writing to a potentially non writable location

2023-01-04 01:09 UTC, netniV commented on cli/convert-to-dsstats.php
> +				if ($reverse == true && $target[5] == 'WeatherMapDataSource_dsstats' && 1 == 0) {
A lot of code follows for something not implemented ?

2023-01-04 01:09 UTC, netniV commented on cli/convert-to-dsstats.php
> +	$copyright_years = '2008-2023';
No point using a varaible for a single use string.  Either make it a common function or just put it in the output

2023-01-04 01:09 UTC, netniV commented on cli/map-tidyup.php
> +	print 'Weathermap Map Tidy Up Tool, Copyright Howard Jones, Version ' . $info['version'] . ', ' . $copyright_years . PHP_EOL;
Again `copyright_years` should be global function or just inserted.  Using a variable is overkill

2023-01-04 01:09 UTC, netniV commented on js/editor.js
> +
Empty functions

2023-01-04 01:09 UTC, netniV commented on lib/WeatherMap.functions.php
> +			cacti_log("DEBUG:$calling_fn " . ($weathermap_map == '' ? '':$weathermap_map . ': ') . rtrim($string), true, 'WEATHERMAP');
No space after colon

2023-01-04 01:09 UTC, netniV commented on lib/WeatherMap.functions.php
> +class Point {
Classes shouldn't be in functions file

2023-01-04 01:09 UTC, netniV commented on lib/editor.inc.php
> +	$sql_where .= ($sql_where != '' ? ' AND ':'WHERE ') . 'gt.hash = "5deb0d66c81262843dce5f3861be9966"';
If this hash is used in multiple places, consider using a constant or configuration item

2023-01-04 01:09 UTC, netniV commented on setup.php
> +}
Empty function?

2023-01-04 01:09 UTC, netniV commented on weathermap-cacti-plugin-mgmt.php
> +		$value     = get_nfilter_request_var('value');
Should this be using the nfilter version?

2023-01-04 01:09 UTC, netniV commented on weathermap-cacti-plugin-mgmt.php
> +	$auth_results = db_fetch_assoc($auth_sql);
Should be a prepared statement

2023-01-04 01:09 UTC, netniV commented on weathermap-cacti-plugin-mgmt.php
> +cacti_log("The map is is: $mapid");
Stray log message?

2023-01-04 01:09 UTC, netniV commented on weathermap-cacti-plugin.php
> +	if (1 == 0) {
This whole section will never run

2023-01-08 18:27 UTC, TheWitness commented on CHANGELOG.md
> +* ADDED  - Drop image functionality for Nodes and Background images
Moving forward, now that we have an issue tracking, it will maintain the correct style.

2023-01-08 18:35 UTC, TheWitness commented on setup.php
> +}
Removed.

2023-01-08 18:37 UTC, TheWitness commented on weathermap-cacti-plugin-mgmt.php
> +		$value     = get_nfilter_request_var('value');
They are both inserted using prepared statements.  For this release, it should be harmless.  I need to spend more time on the WeatherMap Core to understand all these variables and what their potential settings are before locking anything down.  I would prefer to provide curated set of name value pairs rather than random sets.

2023-01-08 18:38 UTC, TheWitness commented on weathermap-cacti-plugin-mgmt.php
> +	$auth_results = db_fetch_assoc($auth_sql);
This section is removed now.

2023-01-08 18:38 UTC, TheWitness commented on weathermap-cacti-plugin-mgmt.php
> +cacti_log("The map is is: $mapid");
Removed.

2023-01-08 18:39 UTC, TheWitness commented on weathermap-cacti-plugin.php
> +	if (1 == 0) {
Removed

2023-01-08 18:40 UTC, TheWitness commented on cli/cacti-mapper.php
> +$data_template_hash = 'fd841e8bb822927289b7acbc031f3d7e';
If it turns out that someone has created their own interface graphs template, and they do a feature request, we can add it.  But at a later date.

2023-01-08 18:40 UTC, TheWitness commented on CHANGELOG.md
> +IMPORTANT NOTE: This version only works on CACTI 1.x++!
Corrected.

2023-01-08 18:40 UTC, TheWitness commented on README.md
> +This is PHP Network Weathermap fork, version 1.0 originally by Howard Jones (howie@thingy.com)
Corrected.

2023-01-08 18:42 UTC, TheWitness commented on cli/cacti-mapper.php
> +
Yea, that's a good point.

2023-01-08 18:45 UTC, TheWitness commented on cli/cacti-mapper.php
> +
Resolved now.

2023-01-08 18:45 UTC, TheWitness commented on cli/cacti-mapper.php
> +$fd = fopen('mapper-cache.txt', 'w');
Resolved now.

2023-01-08 18:46 UTC, TheWitness commented on cli/convert-to-dsstats.php
> +				if ($reverse == true && $target[5] == 'WeatherMapDataSource_dsstats' && 1 == 0) {
Yea, not implemented and not fully rationalized.  Going to have to wait on bugs here.  It's no better or worse than it was.

2023-01-08 18:46 UTC, TheWitness commented on js/editor.js
> +
Yikes.

2023-01-08 18:48 UTC, TheWitness commented on js/editor.js
> +
Resolved.

2023-01-08 18:49 UTC, TheWitness commented on lib/WeatherMap.functions.php
> +			cacti_log("DEBUG:$calling_fn " . ($weathermap_map == '' ? '':$weathermap_map . ': ') . rtrim($string), true, 'WEATHERMAP');
Resolved.

2023-01-08 18:50 UTC, TheWitness commented on lib/WeatherMap.functions.php
> +class Point {
It's a good point.  We'll have to see how Howie goes with his core.  There are a few more like this too.

2023-01-08 18:59 UTC, TheWitness commented on lib/editor.inc.php
> +	$sql_where .= ($sql_where != '' ? ' AND ':'WHERE ') . 'gt.hash = "5deb0d66c81262843dce5f3861be9966"';
Was replaced by a Data Query hash, but not disagreeing.  No change on this for now.

2023-01-08 19:16 UTC, TheWitness commented on cli/map-tidyup.php
> +	print 'Weathermap Map Tidy Up Tool, Copyright Howard Jones, Version ' . $info['version'] . ', ' . $copyright_years . PHP_EOL;
Okay, drafted some for now.  Await Howies response.

2023-01-08 19:21 UTC, TheWitness commented on cli/convert-to-dsstats.php
> +	$copyright_years = '2008-2023';
Got a constant now.

2023-01-08 19:21 UTC, TheWitness commented on README.md
> +
Resolved

2023-01-08 19:22 UTC, TheWitness commented on CHANGELOG.md
> +* FIXED  - General support for PHP 8.2
Fixed in README.md.

2023-01-08 19:22 UTC, TheWitness commented
Okay, Mark.  Got them all addressed.

2023-01-08 19:43 UTC, netniV approved these changes, later dismissed
I'll approve but there are still suggested changes.

2023-01-08 19:43 UTC, netniV commented on README.md
> +beta, yet non-production use at this time.
yet non-production?

2023-01-08 19:43 UTC, netniV commented on README.md
>  [GitHub](https://github.com/cacti)!
Should we also reference Howie's repo?

2023-01-08 19:43 UTC, netniV commented on README.md
> -Copyright (c) 2004-2022 - The Cacti Group, Inc.
Copyright was removed.

2023-01-08 19:43 UTC, netniV commented on lib/datasources/index.php
> +header('Location:../index.php');
Missing copyright

2023-01-08 19:43 UTC, netniV commented on lib/editor.inc.php
> +	$sql_where .= ($sql_where != '' ? ' AND ':'WHERE ') . 'gl.snmp_query_id = (SELECT id FROM snmp_query WHERE hash = "d75e406fdeca4fcef45b8be3a9a63cbc")';
Hash should be a constant

2023-01-08 19:43 UTC, netniV commented on lib/pre/index.php
> +header('Location:../index.php');
missing copyright

2023-01-08 19:54 UTC, TheWitness commented on README.md
> +beta, yet non-production use at this time.
Yea, I don't want to take bullet's until we've had at least a half a dozen give the thumbs up.

2023-01-08 19:57 UTC, TheWitness commented on README.md
> -Copyright (c) 2004-2022 - The Cacti Group, Inc.
Resolved.

2023-01-08 20:14 UTC, TheWitness commented on README.md
>  [GitHub](https://github.com/cacti)!
Added some additional language.

2023-01-08 20:14 UTC, TheWitness commented on README.md
> -Copyright (c) 2004-2022 - The Cacti Group, Inc.
Resolved this one.

2023-01-08 20:15 UTC, TheWitness commented on lib/editor.inc.php
> +	$sql_where .= ($sql_where != '' ? ' AND ':'WHERE ') . 'gl.snmp_query_id = (SELECT id FROM snmp_query WHERE hash = "d75e406fdeca4fcef45b8be3a9a63cbc")';
I will convert to a setting in v1.1

2023-01-08 20:15 UTC, TheWitness commented on lib/pre/index.php
> +header('Location:../index.php');
grr...

2023-01-08 20:29 UTC, thurban approved these changes

2023-01-08 20:33 UTC, netniV approved these changes

2023-01-08 20:41 UTC, bmfmancini approved these changes

2023-01-08 20:51 UTC, netniV approved these changes

2023-01-08 20:51 UTC, cigamit approved these changes

2023-01-08 20:54 UTC, merged